### ISSUE TITLE
Ideas to reuse template binding from Polymer Element

### ISSUE THREAD

**Issue by tomalec** [PuppetJs/templatebinding.org#2]
In worst case we could try to reuse template binding from Polymer Element, by fetching features like:
- [template](https://github.com/Polymer/polymer/blob/0.8-preview/src/features/base/template.html)
- [bind](https://github.com/Polymer/polymer/blob/0.8-preview/src/features/standard/bind.html)
- [annotations](https://github.com/Polymer/polymer/blob/0.8- preview/src/features/standard/annotations.html)
- etc.
  
  form Base 

``` javascript
using("Base", function(Base){ /* use Base.featuredMethodName */});
```

and create own `<puppet-template>` in place of current `<template bind>`

Pros:
- binding engine is consistent,
- and developed by Polymer guys

Cons:
- requires `using`/`Base` to remain global,
- prone to crash on every Polymer internals change, as those methods may not be stable.

**Comment by warpech** [comment]
Archiving this issue... I will archive this repo.
